export default{
    data(){
        let vm=this,query=vm.$route.query,id=query.id;
        return{
            userGroupId:'userGroups',
            userGroupGrid:{
                search:{
                    url:'jfcloud/jf-cloud-platform/security/user/group/page',
                    defaultParams:{userId:id,appCode:vm.$store.state.app.appInfo.appCode},
                    autoLoad:vm.autoLoad('userGroups'),
                },
                delete:{
                    url:'jfcloud/jf-cloud-platform/security/user/group/delete'
                },
                table:{
                    pkId:'id',
                    buttons:[
                        {title:vm.$t('delete'),gridDelete:true}
                    ],
                    permissionCode:'userGroups$delete',
                    logSetting:{module:'UserGroup'},
                    showAuditUpdate:true,
                    columns:[
                        {key:'grantStatus',width:150,render:(h,params)=>{
                            return vm.$util.grantStatus(vm,h,params.row.beginDate,params.row.endDate);
                        },condition:{
                            type:'radio',items:[
                               {value:'1',label:vm.$t('status.grantStatus.1')},
                               {value:'2',label:vm.$t('status.grantStatus.2')},
                               {value:'3',label:vm.$t('status.grantStatus.3')},
                               {value:'4',label:vm.$t('status.grantStatus.4')}
                            ]
                        }},
                        {key:'groupCode',width:150,condition:true},
                        {key:'groupName',width:200,condition:true},
                        {key:'groupDesc',condition:true},
                        {key:'beginDate',width:150,condition:{type:'datePicker',format:'yyyy-MM-dd',width:200}},
                        {key:'endDate',width:150,condition:{type:'datePicker',format:'yyyy-MM-dd',width:200}}
                    ]
                }
            },
            showAddGroup:false,
            addGroupFormData:{userId:id,appCode:vm.$store.state.app.appInfo.appCode},
        }
    },
    methods:{
        loadUserGroups(){
            let userGroupGrid=this.$refs.userGroupGrid;
            if(userGroupGrid){
                userGroupGrid.search();
            }
        },
    }
}