export default{
    data(){
        let vm=this,query=vm.$route.query,id=query.id;
        return{
            userRolesId:'userRoles',
            userRoleGrid:{
                search:{
                    url:'jfcloud/jf-cloud-platform/security/user/role/page',
                    defaultParams:{userId:id,appCode:vm.$store.state.app.appInfo.appCode},
                    autoLoad:vm.autoLoad('userRoles'),
                },
                delete:{
                    url:'jfcloud/jf-cloud-platform/security/user/role/delete'
                },
                table:{
                    pkId:'id',
                    buttons:[
                        {title:vm.$t('delete'),gridDelete:true}
                    ],
                    permissionCode:'userRoles$delete',
                    logSetting:{module:'UserRole'},
                    showAuditUpdate:true,
                    columns:[
                        {key:'grantStatus',width:150,render:(h,params)=>{
                            return vm.$util.grantStatus(vm,h,params.row.beginDate,params.row.endDate);
                        },condition:{
                            type:'radio',items:[
                               {value:'1',label:vm.$t('status.grantStatus.1')},
                               {value:'2',label:vm.$t('status.grantStatus.2')},
                               {value:'3',label:vm.$t('status.grantStatus.3')},
                               {value:'4',label:vm.$t('status.grantStatus.4')}
                            ]
                        }},
                        {key:'roleCode',width:150,condition:true},
                        {key:'roleName',width:200,condition:true},
                        {key:'roleDesc',condition:true},
                        {key:'beginDate',width:150,condition:{type:'datePicker',format:'yyyy-MM-dd',width:200}},
                        {key:'endDate',width:150,condition:{type:'datePicker',format:'yyyy-MM-dd',width:200}}
                    ]
                }
            },
            showAddRole:false,
            addRoleFormData:{userId:id,appCode:vm.$store.state.app.appInfo.appCode},
        }
    },
    methods:{
        loadUserRoles(){
            let userRoleGrid=this.$refs.userRoleGrid;
            if(userRoleGrid){
                userRoleGrid.search();
            }
        },
    }
}