export default{
    //操作类
    operation:'Operation',
    save:'Save',
    edit:'Edit',
    cancel:'Cancel',
    create:'Create',
    search:'Search',
    delete:'Delete',
    detail:'Detail',
    refresh:'Refresh',
    confirm:'Confirm',
    operationLog:'Operation Log',
    tableSetting:'Table Setting',
    advancedFilter:'Advanced Filter',

    //操作提示类
    saveing:'Saveing',
    updateing:'Updateing',
    deleteing:'Deleteing',
    syncing:'Syncing',
    saveSuccessful:'Save Successful',
    updateSuccessful:'Update Successful',
    deleteSuccessful:'Delete Successful',
    syncSuccessful:'Sync Successful',

    //通用字段
    all:'All',
    sortNo:'Sort No',
    mobile:'Mobile',
    email:'Email',
    normal:'Normal',
    lock:'Lock',
    unlock:'Unlock',
    male:'Male',
    female:'Female',
    userSex:'User Sex',
    enable:'Enable',
    logout:'Logout',
    status:'Status',
    grantStatus:'Grant Status',
    beginDate:'Begin Date',
    endDate:'End Date',
    dateRange:'Date Range',
    validated:'Validated',
    noValidated:'No Validated',
    applyStatus:'Apply Status',
    createBy:'Create By',
    createDate:'Create Date',
    lastUpdateBy:'Last Update By',
    lastUpdateDate:'Last Update Date',
    logoTitle:'JF Cloud Platform',
    logoMinTitle:'JF',
    
    //提示类
    selectDateTimeRange:'请选择一个时间范围',
    queryPlaceholder:'请输入搜索条件',
    deleteConfirmOfMsg:'你确定要删除{msg}吗？',
    deleteConfirm:'你确定要删除吗？',
    deleteNodeWarning:'请先删除子级再执行删除操作',
    logoutConfirm:'你确认要退出登录吗？',
    switchLangConfirm:'你确定要切换语言吗？',
    switchAppConfirm:'你确定要切换应用吗？',

    //登录相关
    accontOrMobileOrEmail:'账号、手机号码和邮箱',
    password:'Password',
    validateCode:'Validate Code',
    forgetPassword:'Forget Password',
    passwordLogin:'密码登录',
    mobileLogin:'Mobile Login',
    validCodeTip:'看不清，点击刷新',

    baseInfo:'Base Info',
    updatePassword:'Update Password',
    bindEmailMobile:'Binding Email Mobile',
    myApp:'My App',
    myRole:'My Role',
    mySetting:'My Setting',
    myLogs:'My Logs',
    myPermission:'My Permission',
}