export default{
    //菜单路由
    home:'Home',
    workspace:'Workspace',
    myImport:'My Import',
    myExport:'My Export',
    accountMgt:'Account',
    organizationMgt:'Organization',
    roleMgt:'Role',
    userMgt:'User',
    groupMgt:'Group',
    employeeMgt:'Employee',
    permissionMgt:'Permission',
    appMgt:'App',
    configMgt:'Config',
    menuMgt:'Menu',
    propertyMgt:'Property',
    codeMgt:'Code',
    i18nMgt:'I18n',
    personalizedMgt:'Personalized',
    noticeMgt:'Notice',
    templateMgt:'Message Template',
    importOrExportMgt:'Import & Export',
    importMonitor:'Import Monitor',
    exportMonitor:'Export Monitor',
    importTemplate:'Import Template',
    exportTemplate:'Export Template',
    monitorMgt:'Monitor',
    auditLog:'Audit Log',
    serverLog:'Server Log',
    jobMgt:'Job',

    //非菜单路由
    personal:'Personal',
    login:'Login',
    userDetail:'User Detail',
    groupDetail:'Group Detail',
    appDetail:'App Detail',
    roleDetail:'Role Detail',
    employeeDetail:'Employee Detail'
}