import Main from '@/components/main/index.vue'
import ParentView from '@/components/parent-view/index.vue'
import Home from '@/views/home/index.vue'
import Login from '@/views/login/index.vue'
import Role from '@/views/account/role/index.vue'
import User from '@/views/account/user/index.vue'
export default[
    {
        path: '/',
        name: 'main',
        component: Main,
        meta:{
            mainMenu:true
        },
        children:[
            {
                path:'/home',
                name:'home',
                component:Home,
                meta:{
                    icon:'md-home'
                }
            },
            {
                name:'accountMgt',
                path:'/account',
                component:ParentView,
                meta:{
                    noLink:true,
                    icon:'ios-people'
                },
                children:[
                    {
                        path:'/account/role',
                        name:'roleMgt',
                        component:Role,
                        meta:{
                            icon:'md-people'
                        }
                    },
                    {
                        path:'/account/user',
                        name:'userMgt',
                        component:User,
                        meta:{
                            icon:'md-person'
                        }
                    },
                    {
                        path:'/account/permission',
                        name:'permissionMgt',
                        component:User,
                        meta:{
                            icon:'md-person'
                        }
                    },
                    {
                        path:'/account/group',
                        name:'groupMgt',
                        component:User,
                        meta:{
                            icon:'md-person'
                        }
                    },
                    {
                        path:'/account/app',
                        name:'appMgt',
                        component:User,
                        meta:{
                            icon:'md-person'
                        }
                    },
                ]
            },
            {
                name:'configMgt',
                path:'/config',
                component:ParentView,
                meta:{
                    noLink:true,
                    icon:'ios-people'
                },
                children:[
                    {
                        path:'/config/property',
                        name:'propertyMgt',
                        component:Role,
                        meta:{
                            icon:'md-people'
                        }
                    },
                    {
                        path:'/config/i18n',
                        name:'i18nMgt',
                        component:User,
                        meta:{
                            icon:'md-person'
                        }
                    },
                    {
                        path:'/config/code',
                        name:'codeMgt',
                        component:User,
                        meta:{
                            icon:'md-person'
                        }
                    },
                    {
                        path:'/config/personalized',
                        name:'personalizedMgt',
                        component:User,
                        meta:{
                            icon:'md-person'
                        }
                    }
                ]
            }
        ]
    },
    {
        path:'/login',
        name:'login',
        component:Login
    }
]