export default{
    type:{
        appType:{
            1:'系统应用',
            2:'业务应用'
        },
        userType:{
            1:'员工',
            2:'注册用户'
        },
        employeeType:{
            1:'全职',
            2:'兼职',
            3:'试用'
        },
        logType:{
            audit:'审计',
            login:'登录',
            performance:'性能'
        },
        userSex:{
            1:'男',
            2:'女'
        }
    },
    status:{
        userStatus:{
            'Y':'正常',
            'L':'锁定',
            'D':'删除'
        },
        employeeStatus:{
            '1':'在职',
            '2':'离职'
        },
        applyStatus:{
            'Y':'可申请',
            'N':'不可申请'
        },
        grantStatus:{
            1:'未生效',
            2:'正常',
            3:'即将过期',
            4:'已过期'
        }
    }
}