export default{
    data(){
        let vm=this,query=vm.$route.query,id=query.id;
        return{
            groupUsersId:'groupUsers',
            groupUserGrid:{
                search:{
                    url:'jfcloud/jf-cloud-platform/security/group/user/page',
                    defaultParams:{groupId:id},
                    autoLoad:vm.autoLoad('groupUsers'),
                },
                delete:{
                    url:'jfcloud/jf-cloud-platform/security/group/user/delete'
                },
                table:{
                    pkId:'id',
                    buttons:[
                        {title:vm.$t('delete'),gridDelete:true}
                    ],
                    permissionCode:'groupUsers$delete',
                    logSetting:{module:'GroupUser'},
                    showAuditUpdate:true,
                    columns:[
                        {key:'grantStatus',width:150,render:(h,params)=>{
                            return vm.$util.grantStatus(vm,h,params.row.beginDate,params.row.endDate);
                        },condition:{
                            type:'radio',items:[
                               {value:'1',label:vm.$t('status.grantStatus.1')},
                               {value:'2',label:vm.$t('status.grantStatus.2')},
                               {value:'3',label:vm.$t('status.grantStatus.3')},
                               {value:'4',label:vm.$t('status.grantStatus.4')}
                            ]
                        }},
                        {key:'userId',format:'user',title:'userName',condition:{type:'string',key:'userName'}},
                        {key:'beginDate',width:150,condition:{type:'datePicker',format:'yyyy-MM-dd',width:200}},
                        {key:'endDate',width:150,condition:{type:'datePicker',format:'yyyy-MM-dd',width:200}}
                    ]
                }
            },
            showAddUser:false,
            addUserFormData:{groupId:id},
        }
    },
    methods:{
        loadGroupUsers(){
            let groupUserGrid=this.$refs.groupUserGrid;
            if(groupUserGrid){
                groupUserGrid.search();
            }
        },
    }
}